=== garciarodriguezcristian/Apuntes/Lenguaje de marcas/Apuntes/UD1 XML DTD XSD/Ejercicios/Repaso/XSD y XML/ej_05_agencia_viajes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agencia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paquete" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="destino">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z ]+"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minExclusive value="0"/>
                                        <xs:pattern value="[0-9].+\.[0-9].+"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fechaInicio" type="xs:date"></xs:element>
                            <xs:element name="fechaFin" type="xs:date"></xs:element>
                            <xs:element name="tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Aventura"></xs:enumeration>
                                        <xs:enumeration value="Relax"></xs:enumeration>
                                        <xs:enumeration value="Cultural"></xs:enumeration>
                                        <xs:enumeration value="Familiar"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cliente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z].*"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="edad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="18"></xs:minInclusive>
                                                    <xs:maxInclusive value="99"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="email">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="PKT-\d{4}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== garciarodriguezcristian/Apuntes/Lenguaje de marcas/Apuntes/Ejercicios/Repaso/XSD y XML/ej_05_agencia_viajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<agencia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej_05_agencia_viajes.xsd">

    <paquete codigo="PKT-0000">
        <destino>Las Palmas</destino>
        <precio>300.50</precio>
        <fechaInicio>2025-04-10</fechaInicio>
        <fechaFin>2025-04-20</fechaFin>
        <tipo>Relax</tipo>
        <cliente>
            <nombre>Elisabeth</nombre>
            <dni>75573283N</dni>
            <edad>26</edad>
            <email>correo@stem.com</email>
        </cliente>
    </paquete>
    <paquete codigo="PKT-1245">
        <destino>Congo</destino>
        <precio>300.50</precio>
        <fechaInicio>2025-04-10</fechaInicio>
        <fechaFin>2025-12-30</fechaFin>
        <tipo>Aventura</tipo>
        <cliente>
            <nombre>Elisabeth</nombre>
            <dni>75573283N</dni>
            <edad>26</edad>
            <email>correo@stem.com</email>
        </cliente>
    </paquete>

</agencia>
