<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE curso [
    <!ELEMENT curso (nombre,alumno+)>
    <!ELEMENT alumno (nombre,apellido)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
]>

<curso>
    <nombre>DAW</nombre>
    <alumno>
        <nombre>Alu1</nombre>
        <apellido>Ape1</apellido>
    </alumno>
    <alumno>
        <nombre>Alu2</nombre>
        <apellido>Alu2</apellido>
    </alumno>
</curso>