=== garciarodriguezcristian/Apuntes/Lenguaje de marcas/Apuntes/UD1 XML DTD XSD/Ejercicios/Relacion3/liga.dtd
<!-- Hago el DTD externo y defino las reglas a seguir
en el .xml. 
La liga es la raiz, y tiene que tener mÃ¡s de un entrenador (+),
cada entrenador varios pokemons (+)
y cada pokemon puede tener 1 o mas "tipo" (+)-->
<!ELEMENT liga (entrenador+)>
<!ELEMENT entrenador (nombre,pokemon+)>
<!ELEMENT pokemon (nombre,tipo+,nivel)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>

=== garciarodriguezcristian/Apuntes/Lenguaje de marcas/Apuntes/Ejercicios/Relacion3/liga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Ejercicio 3 — Liga Pokémon con DTD externa-->

<!-- Defino el DTD con <!DOCTYPE liga SYSTEM " nombre_del_archivo.dtd ".
Dentro del archivo "liga.dtd" están todos los "<!ELEMENT", siendo la raiz "liga"-->
<!DOCTYPE liga SYSTEM "liga.dtd">

<!--Defino el .xml siguiendo las reglas del DTD externo.
* Escribe liga.xml con al menos 2 entrenadores.
* Cada entrenador debe tener mínimo 2 Pokémon.
* Escribe también liga.dtd con las reglas.-->
<liga>
    <entrenador>
        <nombre>Ash Ketchum</nombre>
        <pokemon>
            <nombre>Bulbasur</nombre>
            <tipo>Planta</tipo>
            <tipo>Veneno</tipo>
            <nivel>24</nivel>
        </pokemon>
        <pokemon>
            <nombre>Pikachu</nombre>
            <tipo>Electrico</tipo>
            <nivel>15</nivel>
        </pokemon>
    </entrenador>
    <entrenador>
        <nombre>Misty</nombre>
        <pokemon>
            <nombre>Charmander</nombre>
            <tipo>Fuego</tipo>
            <nivel>17</nivel>
        </pokemon>
        <pokemon>
            <nombre>Squirtle</nombre>
            <tipo>Agua</tipo>
            <nivel>54</nivel>
        </pokemon>
    </entrenador>
</liga>
